title: "Nelsito Learning Journey"
description: "Documentando mi viaje en programación y tecnología"
baseurl: ""  #cambiar luego si no está en raíz.
url: "https://nelsitoprogramador.github.io"
theme: minima
